name: joshbaurle
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#422f2b'
    - '#7a5b3f'
    - '#fed9a2'
    - '#120602'
  brandStrength: 0.9748931399080902
  lightness: 0.16792206768877804
  saturation: 0.44949974212795496
  rhythmicContrast: 0.75
purpose: []
