name: joshbaurle
favicon: null
layout_spectrum: 0.18745953124016523
typography_spectrum: 0.0982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a96a2'
    - '#313155'
    - '#eef5fd'
    - '#9fc7fd'
    - '#010103'
  brandStrength: 0.9748931399080902
  lightness: 0.16792206768877804
  saturation: 0.44949974212795496
  rhythmicContrast: 0.75
purpose: []
