name: joshbaurle
favicon: null
layout_spectrum: 0.18745953124016523
typography_spectrum: 0.0982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9748931399080902
  lightness: 0.16792206768877804
  saturation: 0.44949974212795496
  rhythmicContrast: 0.6398676470853388
purpose: []
