name: joshbaurle
favicon: null
layout_spectrum: 0.75979
typography_spectrum: 0.47267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#422f2b'
    - '#7a5b3f'
    - '#fed9a2'
    - '#120602'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
